#if !canImport(ObjectiveC)
  import XCTest

  extension PrchNIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrchNIOTests = [
      ("testNIO", testNIO)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(PrchNIOTests.__allTests__PrchNIOTests)
    ]
  }
#endif
