name: Sublimation
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  Sublimation:
    path: .
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lints.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
