name: Sublimation
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  Sublimation:
    path: .
projectReferences:
    Demo:
      path: ./Demo/SublimationDemoApp.xcodeproj
    Multipeer:
      path: ./Reference/MultipeerDemo/MultipeerDemo.xcodeproj
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
