name: Sublimation
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  Prch:
    path: .
rojectReferences:
    YamsProject:
      path: ./Demo/SublimationDemoApp.xcodeproj
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
