name: Sublimation
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  Sublimation:
    path: .
  SublimationNgrok: 
    path: Packages/SublimationNgrok
  SublimationService: 
    path: Packages/SublimationService
  SublimationVapor: 
    path: Packages/SublimationVapor
  Ngrokit: 
    path: Packages/Ngrokit
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
