# .github/workflows/main.yml
name: Main Workflow

on: push

jobs:
  trigger_sub_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Sub Workflows
        uses: ./.github/actions/trigger-sub-workflows
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}