name: Children

on: push

jobs:
  trigger_sub_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SubDirectory Workflows
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = github.getOctokit(core.getInput('github_token'));
            const workflows = [
              'Packages/Ngrokit/.github/workflows/Ngrokit.yml',
              'Packages/SublimationBonjour/.github/workflows/SublimationBonjour.yml',
              'Packages/SublimationNgrok/.github/workflows/SublimationNgrok.yml',
              'Packages/SublimationService/.github/workflows/SublimationService.yml',
              'Packages/SublimationVapor/.github/workflows/SublimationVapor.yml'
            ];
            for (const workflow of workflows) {
              await octokit.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflow,
                ref: context.ref,
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}